name: pf_g10 # You can also change this to another name to avoid warning with existing group.
services:
  backend:
    container_name: pj-backend
    build: .
    ports:
      - ${PORT}:3000
    # env_file:
    #   - .env   
    networks:
      - pf_g10_pf-net
    environment:
      # - NODE_ENV=production
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    volumes:
      - ./logs:/app/logs
    post_start:
      - command:
          [
            "sh",
            "-c",
            'npm run db:migrate | awk ''{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0; fflush(); }'' | tee -a /app/logs/migration.log',
          ]
networks:
  pf_g10_pf-net: # Check by using `docker network ls` command
    external: true